# ⭐ This file is the same as the last one, EXCEPT for the tag-name-variable ":$COMMIT_SHA" added to end of app name (5 places) .
# ⭐ This variable holds a unique identifier for each build, which is the commit SHA of the source code.
# ⭐ A new COMMIT_SHA is created each time a code update is pushed/ committed to the repository.
# ⭐ Using this unique SHA in any step of cloudbuild.yaml allows us to trace that step to a specific code change.
# ⭐ This helps with debugging, tracking, and managing different versions of the application. 
steps:
# step 1: build app & tag it
- name: 'gcr.io/cloud-builders/docker' 
  args: ['build', '-t', 'us-central1-docker.pkg.dev/umlops/gcr-umlops/demo-flask-app-cb1:$COMMIT_SHA', '.'] # Added ":$COMMIT_SHA" to end of app name

# step 2: push app to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/umlops/gcr-umlops/demo-flask-app-cb1:$COMMIT_SHA']

# step 3: run tests	
- name: 'us-central1-docker.pkg.dev/umlops/gcr-umlops/demo-flask-app-cb1:$COMMIT_SHA'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
      python -m pytest

# step 4: deploy app to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk' 
  entrypoint: gcloud
  args:
   - 'run'
   - 'deploy'
   - 'demo-flask-app-cb1'
   - '--image'
   - 'us-central1-docker.pkg.dev/umlops/gcr-umlops/demo-flask-app-cb1:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
   - '--allow-unauthenticated'

# Make the image available for later reference, deployment, or use in other build steps.
images:
- 'us-central1-docker.pkg.dev/umlops/gcr-umlops/demo-flask-app-cb1:$COMMIT_SHA'

# Set the build option to send all build logs only to Google Cloud Logging (not to the Cloud Build UI).
options:
  logging: CLOUD_LOGGING_ONLY
